# MOZNOSTI ANALYZY KODU POVODNE ZOBRATE PRIAMO Z FLUTTER PROJEKTU NA GITHUBE
analyzer:
  strong-mode:
    implicit-dynamic: false
  errors:
    # AK NEBOLI DODANE POVINNE PARAMETRE, ZOBRAZUJ TO AKO WARNING A NIE AKO HINT
    missing_required_param: warning
    # CHYBAJUCE RETURNY ZOBRAZUJ AKO WARNING A NIE AKO HINT
    missing_return: warning
    # IGNORUJ TODOs
    todo: ignore
  exclude:
    - 'lib/main.reflectable.dart'
    - 'lib/generated_plugin_registrant.dart'
linter:
  rules:
    - always_declare_return_types
    - always_put_control_body_on_new_line
    - always_put_required_named_parameters_first
    - always_specify_types
    - annotate_overrides
    # NEMOZE SA ZAPNUT AK CHCEME MAT VZDY SPECIFIKOVANY TYP (always_specify_types)
    # - avoid_annotating_with_dynamic
    # VYPNUTE LEBO OD DART VERZIE 2.1 UZ NIE JE KONTROLA NA AS 'EXPENSIVE' PRE AOT MODE
    # - avoid_as
    # VYPNUTE LEBO JE TO PRE JAVISTU TAZKO CITATELNY ZAPIS
    # - avoid_bool_literals_in_conditional_expressions
    - avoid_catches_without_on_clauses
    - avoid_catching_errors
    # MY CHCEME MAT MOZNOST ZGRUPOVAT UTIL METODY POD TRIEDU
    # - avoid_classes_with_only_static_members
    # VALIDANE LEN PRI DART2JS
    # - avoid_double_and_int_checks
    - avoid_empty_else
    - avoid_field_initializers_in_const_classes
    - avoid_function_literals_in_foreach_calls
    - avoid_init_to_null
    # VALIDANE LEN PRI DART2JS
    # - avoid_js_rounded_ints
    - avoid_null_checks_in_equality_operators
    # - avoid_positional_boolean_parameters # not yet tested
    # - avoid_private_typedef_functions # we prefer having typedef (discussion in https://github.com/flutter/flutter/pull/16356)
    - avoid_relative_lib_imports
    - avoid_renaming_method_parameters
    - avoid_return_types_on_setters
    - avoid_returning_this
    - avoid_setters_without_getters
    - avoid_single_cascade_in_expression_statements
    - avoid_slow_async_io
    - avoid_types_as_parameter_names
    # NEMOZE SA ZAPNUT AK CHCEME MAT VZDY SPECIFIKOVANY TYP (always_specify_types)
    # - avoid_types_on_closure_parameters
    - avoid_unused_constructor_parameters
    - avoid_void_async
    - await_only_futures
    - camel_case_types
    - cancel_subscriptions
    - cascade_invocations
    - close_sinks
    - comment_references
    # MY CHCEME MAT KONSTANTY UPPER_CASE, LAHSIE SA TO TAK CITA
    # - constant_identifier_names
    - control_flow_in_finally
    - curly_braces_in_flow_control_structures
    - directives_ordering
    - empty_catches
    - empty_constructor_bodies
    - empty_statements
    - file_names
    - hash_and_equals
    - implementation_imports
    - join_return_with_assignment
    - library_names
    - library_prefixes
    # MY CHCEME MAT RIADKY DLHSIE AKO 80 ZNAKOV. 80 JE PRIKRATKE AK CHCEME DODRZIAVAT PRAVIDLO JASNEHO POMENUVAVANIA
    # - lines_longer_than_80_chars
    - literal_only_boolean_expressions
    - no_adjacent_strings_in_list
    - no_duplicate_case_values
    - non_constant_identifier_names
    - null_closures  # not yet tested
    # NEMOZE SA ZAPNUT AK CHCEME MAT VZDY SPECIFIKOVANY TYP (always_specify_types)
    # - omit_local_variable_types
    - one_member_abstracts
    - only_throw_errors
    # POTREBUJEME OVERRIDOVAT FIELDY V DOMENOVYCH OBJEKTOCH. VDAKA TOMU VIEME MENIT CHOVANIE V ZI
    # - overridden_fields
    - package_names
    - package_prefixed_library_names
    - parameter_assignments
    - prefer_adjacent_string_concatenation
    - prefer_asserts_in_initializer_lists
    - prefer_collection_literals
    - prefer_conditional_assignment
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - prefer_constructors_over_static_methods
    - prefer_contains
    # NECHCEME PRE VIAC RIADKOVE METODY POUZIVAT SKRATENY ZAPIS, JE TO NEPREHLADNE
    # - prefer_expression_function_bodies
    - prefer_final_fields
    - prefer_final_locals
    - prefer_foreach
    - prefer_function_declarations_over_variables
    - prefer_generic_function_type_aliases
    - prefer_initializing_formals
    - prefer_interpolation_to_compose_strings
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_iterable_whereType
    - prefer_single_quotes
    - prefer_typing_uninitialized_variables
    - prefer_void_to_null
    - public_member_api_docs
    - recursive_getters
    - slash_for_doc_comments
    - sort_constructors_first
    - sort_unnamed_constructors_first
    - test_types_in_equals
    - throw_in_finally
    - type_annotate_public_apis
    - type_init_formals
    - unawaited_futures
    - unnecessary_brace_in_string_interps
    - unnecessary_const
    - unnecessary_getters_setters
    # VYPNUTE LEBO JE TO PRE JAVISTU TAZKO CITATELNY ZAPIS
    # - unnecessary_lambdas
    - unnecessary_new
    - unnecessary_null_aware_assignments
    - unnecessary_null_in_if_null_operators
    - unnecessary_overrides
    - unnecessary_parenthesis
    - unnecessary_statements
    - unnecessary_this
    - unrelated_type_equality_checks
    - use_rethrow_when_possible
    - use_setters_to_change_properties
    - use_string_buffers
    - use_to_and_as_if_applicable
    - valid_regexps
    - void_checks